# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import plotly.graph_objects as go

    # shinywidgets asigna un comm propio; Plotly 7 solo acepta el de Jupyter.
    _comm = go.FigureWidget.class_traits()["comm"]
    _comm.validate = lambda obj, value: value

    import shinywidgets._comm as _shiny_comm

    _shiny_comm.OrphanedShinyComm.kernel = None

    import db
    import graficas
    import pandas as pd
    from shiny import reactive, render
    from shiny.express import input, ui
    from shinywidgets import render_plotly

    datos = db.cargar_tablero()

    # ========================================================================

    ui.input_select(
        "anio",
        "Año",
        choices=[db.TODOS, *datos["anios"]],
        selected=datos["anios"][0] if datos["anios"] else db.TODOS,
    )
    ui.input_selectize(
        "departamento",
        "Departamento",
        choices=[db.TODOS, *datos["departamentos"]],
        selected=db.TODOS,
        width="100%",
    )

    @render.ui
    def filtro_municipio():
        return ui.input_selectize(
            "municipio",
            "Municipio",
            choices=db.opciones_municipio(datos["municipios"], input.departamento()),
            selected=db.TODOS,
            width="100%",
            options={"maxOptions": 5000, "placeholder": "Buscar municipio"},
        )

    ui.input_selectize(
        "causa",
        "Causa de defunción",
        choices=datos["causas_opciones"],
        selected=db.TODAS,
        width="100%",
        options={"maxOptions": 200, "placeholder": "Buscar causa"},
    )

    # ========================================================================

    def _anio():
        return input.anio() or db.TODOS


    def _depto():
        return input.departamento() or db.TODOS


    def _muni():
        return input.municipio() or db.TODOS


    def _causa():
        return input.causa() or db.TODAS


    @reactive.calc
    def nac_territorio():
        return db.filtrar_territorio(datos["nacimientos"], _depto(), _muni())


    @reactive.calc
    def def_territorio():
        return db.filtrar_territorio(datos["defunciones"], _depto(), _muni())


    @reactive.calc
    def causas_territorio():
        return db.filtrar_territorio(datos["causas"], _depto(), _muni())


    @reactive.calc
    def panorama():
        nac = db.filtrar_anio(nac_territorio(), _anio())
        defs = db.filtrar_anio(def_territorio(), _anio())
        nacimientos = int(nac["nacimientos"].sum())
        defunciones = int(defs["defunciones"].sum())
        return {
            "nacimientos": nacimientos,
            "defunciones": defunciones,
            "nac_sexo": nac.groupby("sexo")["nacimientos"].sum(),
            "def_sexo": defs.groupby("sexo")["defunciones"].sum(),
        }


    @reactive.calc
    def causas_anio():
        return db.filtrar_anio(causas_territorio(), _anio())


    @reactive.calc
    def causas_filtro():
        frame = causas_anio()
        if _causa() != db.TODAS:
            frame = frame[frame["cod_causa"] == _causa()]
        return frame

    # ========================================================================

    @render.text
    def kpi_nacimientos():
        return graficas.entero(panorama()["nacimientos"])

    # ========================================================================

    @render.text
    def kpi_defunciones():
        return graficas.entero(panorama()["defunciones"])

    # ========================================================================

    @render.text
    def kpi_relacion():
        vista = panorama()
        if vista["nacimientos"] == 0:
            return "—"
        relacion = 100 * vista["defunciones"] / vista["nacimientos"]
        return f"{relacion:.1f}".replace(".", ",")

    # ========================================================================

    @render.text
    def kpi_diferencia():
        vista = panorama()
        diferencia = vista["nacimientos"] - vista["defunciones"]
        texto = graficas.entero(abs(diferencia))
        if diferencia < 0:
            return f"−{texto}"
        return texto

    # ========================================================================

    @render_plotly
    def grafica_evolucion():
        nac = (
            nac_territorio()
            .groupby("anio", as_index=False)["nacimientos"]
            .sum()
        )
        defs = (
            def_territorio()
            .groupby("anio", as_index=False)["defunciones"]
            .sum()
        )
        serie = pd.DataFrame({"anio": [int(a) for a in datos["anios"][::-1]]})
        serie = serie.merge(nac, on="anio", how="left").merge(defs, on="anio", how="left")
        serie[["nacimientos", "defunciones"]] = serie[["nacimientos", "defunciones"]].fillna(0)
        return (graficas.evolucion(serie, _anio()))

    # ========================================================================

    @render_plotly
    def grafica_ranking():
        nac = db.filtrar_anio(nac_territorio(), _anio())
        defs = db.filtrar_anio(def_territorio(), _anio())
        if _depto() == db.TODOS and _muni() == db.TODOS:
            columna = "departamento"
        else:
            columna = "municipio"
        nac_g = nac.groupby(columna, as_index=False)["nacimientos"].sum()
        def_g = defs.groupby(columna, as_index=False)["defunciones"].sum()
        tabla = def_g.merge(nac_g, on=columna, how="outer").fillna(0)
        tabla = tabla.rename(columns={columna: "etiqueta"})
        tabla = tabla.sort_values("defunciones", ascending=False).head(10)
        return (graficas.ranking(tabla))

    # ========================================================================

    @render_plotly
    def grafica_sexo():
        vista = panorama()
        return (graficas.comparacion_sexo(vista["nac_sexo"], vista["def_sexo"]))

    # ========================================================================

    @render_plotly
    def grafica_mapa():
        nac = db.filtrar_anio(nac_territorio(), _anio())
        defs = db.filtrar_anio(def_territorio(), _anio())
        columnas = ["cod_departamento", "departamento", "cod_municipio", "municipio"]
        nac_g = nac.groupby(columnas, as_index=False)["nacimientos"].sum()
        def_g = defs.groupby(columnas, as_index=False)["defunciones"].sum()
        puntos = def_g.merge(nac_g, on=columnas, how="outer").fillna(0)
        puntos = puntos.merge(datos["coords"], on=["cod_departamento", "cod_municipio"], how="inner")
        puntos = puntos[(puntos["defunciones"] > 0) | (puntos["nacimientos"] > 0)]
        if puntos.empty:
            return (graficas.figura_vacia("No hay coordenadas para este territorio.", 520))
        puntos = puntos.copy()
        puntos["tamano"] = puntos["defunciones"].clip(lower=1)
        return (graficas.mapa(puntos, _depto()))

    # ========================================================================

    @render.text
    def kpi_def_causa():
        return graficas.entero(causas_filtro()["defunciones"].sum())

    # ========================================================================

    @render.text
    def kpi_participacion():
        total = int(causas_anio()["defunciones"].sum())
        parte = int(causas_filtro()["defunciones"].sum())
        if total == 0:
            return "—"
        return f"{100 * parte / total:.1f}%".replace(".", ",")

    # ========================================================================

    @render.text
    def kpi_causa_lider():
        if _causa() != db.TODAS:
            nombre = datos["causas_opciones"].get(_causa(), _causa())
        else:
            frame = causas_anio()
            if frame.empty:
                return "—"
            nombre = (
                frame.groupby("causa")["defunciones"].sum().sort_values(ascending=False).index[0]
            )
        nombre = str(nombre)
        return nombre if len(nombre) <= 48 else nombre[:47] + "…"

    # ========================================================================

    @render.text
    def kpi_hombres():
        frame = causas_filtro()
        total = int(frame["defunciones"].sum())
        if total == 0:
            return "—"
        hombres = int(frame.loc[frame["sexo"] == "Hombres", "defunciones"].sum())
        return f"{100 * hombres / total:.1f}%".replace(".", ",")

    # ========================================================================

    @render_plotly
    def grafica_causas():
        frame = causas_anio()
        if frame.empty:
            return (graficas.figura_vacia("No hay causas para este filtro."))
        tabla = (
            frame.groupby(["cod_causa", "causa"], as_index=False)["defunciones"]
            .sum()
            .sort_values("defunciones", ascending=False)
        )
        if _causa() != db.TODAS and _causa() not in set(tabla.head(12)["cod_causa"]):
            extra = tabla[tabla["cod_causa"] == _causa()]
            tabla = pd.concat([tabla.head(11), extra], ignore_index=True)
        else:
            tabla = tabla.head(12)
        return (graficas.barras_causas(tabla, _causa()))

    # ========================================================================

    @render_plotly
    def grafica_piramide():
        return (graficas.piramide(causas_filtro()))

    # ========================================================================

    @render_plotly
    def grafica_tendencia_sexo():
        frame = causas_territorio()
        if _causa() != db.TODAS:
            frame = frame[frame["cod_causa"] == _causa()]
        if frame.empty:
            return (graficas.figura_vacia("No hay serie para esta causa."))
        serie = frame.groupby(["anio", "sexo"], as_index=False)["defunciones"].sum()
        return (graficas.tendencia_sexo(serie, _anio()))

    # ========================================================================

    @render_plotly
    def grafica_donde():
        frame = causas_filtro()
        if frame.empty:
            return (graficas.figura_vacia("No hay territorios para esta causa."))
        columna = "municipio" if _depto() != db.TODOS or _muni() != db.TODOS else "departamento"
        tabla = frame.groupby(columna, as_index=False)["defunciones"].sum()
        tabla = tabla.rename(columns={columna: "etiqueta"})
        tabla = tabla.sort_values("defunciones", ascending=False).head(12)
        return (graficas.barras_territorio(tabla))

    # ========================================================================



    return None


_static_assets = ["index_files","index_files\\libs\\quarto-html\\tippy.css","index_files\\libs\\quarto-html\\quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css","index_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css","index_files\\libs\\bootstrap\\bootstrap-icons.css","index_files\\libs\\bootstrap\\bootstrap-9339414a91cc698c00d344791dd01023.min.css","index_files\\libs\\bootstrap\\bootstrap-dark-9339414a91cc698c00d344791dd01023.min.css","index_files\\libs\\clipboard\\clipboard.min.js","index_files\\libs\\quarto-html\\quarto.js","index_files\\libs\\quarto-html\\tabsets\\tabsets.js","index_files\\libs\\quarto-html\\popper.min.js","index_files\\libs\\quarto-html\\tippy.umd.min.js","index_files\\libs\\quarto-html\\anchor.min.js","index_files\\libs\\bootstrap\\bootstrap.min.js","index_files\\libs\\quarto-dashboard\\quarto-dashboard.js","index_files\\libs\\quarto-dashboard\\stickythead.js","index_files\\libs\\quarto-dashboard\\web-components.js","index_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "index.html",
    server,
    static_assets=_static_assets,
)
